Update optimized-workflow.yml

diff --git a/.github/workflows/optimized-workflow.yml b/.github/workflows/optimized-workflow.yml
--- a/.github/workflows/optimized-workflow.yml
+++ b/.github/workflows/optimized-workflow.yml
@@ -12,11 +12,11 @@ jobs:
         steps:
         - name: Checkout Repository # name: Custom name for the step 
           uses: actions/checkout@v3 # uses: Use a pre-built action
-        - name: Simulate Failure in test_setup job
-          run: |
-              echo "Running job1"
-              # Simulate a failure or success
-              exit 0  # Change to exit 1 to simulate failure
+        # - name: Simulate Failure in test_setup job
+        #   run: |
+        #       echo "Running job1"
+        #       # Simulate a failure or success
+        #       exit 0  # Change to exit 1 to simulate failure
         - name: Install dependencies
           run: npm ci
         - name: Install Playwright Browsers
@@ -27,8 +27,10 @@ jobs:
         runs-on: WINDOWS10HOST
         # needs: test_setup
         # if: ${{ needs.test_setup.result == 'success' || always() }}
-        needs: test_setup
-        if: ${{ needs.test_setup.result == 'success' }}
+        # needs: test_setup
+        # if: ${{ needs.test_setup.result == 'success' }}
+        needs:
+            - test_setup
         steps:
         # - name: Checkout Repository # name: Custom name for the step 
         #   uses: actions/checkout@v3 # uses: Use a pre-built action
@@ -52,8 +54,12 @@ jobs:
         # if: ${{ needs.smoke_tests.result == 'success' }}
         # needs: smoke_tests
         # if: ${{ needs.test_setup.result == 'success' || always() }}
-        needs: smoke_tests
-        if: ${{ needs.smoke_tests.result == 'success' || needs.smoke_tests.result == 'failure' }}
+        # needs: smoke_tests
+        # if: ${{ needs.smoke_tests.result == 'success' || needs.smoke_tests.result == 'failure' }}
+        needs: 
+            - test_setup
+            - smoke_tests
+        if: always()
         steps:
         # - name: Checkout Repository # name: Custom name for the step 
         #   uses: actions/checkout@v3 # uses: Use a pre-built action
@@ -78,8 +84,12 @@ jobs:
         # if: ${{ needs.sanity_tests.result == 'success' }}
         # needs: sanity_tests
         # if: ${{ needs.test_setup.result == 'success' || always() }}
-        needs: sanity_tests
-        if: ${{ needs.sanity_tests.result == 'success' || needs.sanity_tests.result == 'failure' }}
+        # needs: sanity_tests
+        # if: ${{ needs.sanity_tests.result == 'success' || needs.sanity_tests.result == 'failure' }}
+        needs: 
+            - test_setup
+            - sanity_tests
+        if: always()
         steps:
         # - name: Checkout Repository # name: Custom name for the step 
         #   uses: actions/checkout@v3 # uses: Use a pre-built action
